apiVersion: v1
kind: ConfigMap
metadata:
  name: zerovault-config
  namespace: zero-vault
  labels:
    app: zero-vault
data:
  JWT_ALGORITHM: "HS256"
  JWT_EXPIRATION_MINUTES: "60"
  CORS_ORIGINS: "*"
  TZ: "Asia/Colombo"
