apiVersion: apps/v1
kind: Deployment
metadata:
  name: zero-vault
  namespace: zero-vault
  labels:
    app: zero-vault
spec:
  replicas: 1
  selector:
    matchLabels:
      app: zero-vault
  template:
    metadata:
      labels:
        app: zero-vault
    spec:
      containers:
      - name: zero-vault-app
        image: surajadev/zero-vault:latest
        ports:
        - containerPort: 8000
        resources:
          requests:
            memory: "128Mi"
            cpu: "125m"
          limits:
            memory: "256Mi"
            cpu: "250m"
        envFrom:
        - configMapRef:
            name: zerovault-config
        env:
        - name: DATABASE_URL
          valueFrom:
            secretKeyRef:
              name: zerovault-secret
              key: db-url
        - name: JWT_SECRET_KEY
          valueFrom:
            secretKeyRef:
              name: zerovault-secret
              key: jwt-secret-key
        livenessProbe:
          httpGet:
            path: /health
            port: 8000
          initialDelaySeconds: 40
          periodSeconds: 30
          timeoutSeconds: 10
          failureThreshold: 3
        readinessProbe:
          httpGet:
            path: /health
            port: 8000
          initialDelaySeconds: 10
          periodSeconds: 10
          timeoutSeconds: 5
          failureThreshold: 3
