apiVersion: v1
kind: Secret
metadata:
  name: zerovault-secret
  namespace: zero-vault
  labels:
    app: zero-vault
type: Opaque
stringData:
  db-url: "${DATABASE_URL}"
  jwt-secret-key: "${JWT_SECRET_KEY}"
